# حداقل رشد از کف
MIN_RISE_FROM_LOW = 50.0

# حداقل امتیاز
MIN_SCORE = 85

# پامپ قوی
PUMP_PERCENT = 15.0

# مقاومت‌ها
DAILY_RESISTANCE_DISTANCE = 2.0
THREE_DAY_RESISTANCE_DISTANCE = 3.0
WEEKLY_RESISTANCE_DISTANCE = 5.0

# حجم
VOLUME_MULTIPLIER = 3.0

# جلوگیری از تکرار
ALERT_COOLDOWN = 7200